#!/bin/bash

set -e

DIR="$(dirname "$0")"
ENVSCRIPT="$1"
TARGETDIR="$2"

source "$DIR/$ENVSCRIPT"

rm -rf "$DIR/tmp"
mkdir "$DIR/tmp"
cd "$DIR/tmp"
wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2k.tar.gz
tar xf openssl-*.tar.gz
rm openssl-*.tar.gz
cd openssl-*
./Configure shared android
make CALC_VERSIONS="SHLIB_COMPAT=; SHLIB_SOVER=" build_libs -j4
cp libcrypto.so libssl.so "$TARGETDIR"
