name: opentodolist
version: git
confinement: strict
grade: stable
base: core20
adopt-info: opentodolist # part to adopt appstream data from (first in parse list)
apps:
    opentodolist:
        command: usr/bin/OpenTodoList-launcher
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop
        - desktop-legacy
        - wayland
        common-id: net.rpdev.OpenTodoList
        desktop: "usr/share/applications/net.rpdev.OpenTodoList.desktop"

parts:
    opentodolist:
        plugin: dump
        source: ./
        parse-info: [net.rpdev.OpenTodoList.appdata.xml]
        override-build: ./ci/snapcraft-build.sh
        stage-packages:
            - libx11-6
            - libxcb1
            - libegl1
            - libgl1
            - libglx0
            - libopengl0
            - libfontconfig1
            - libfreetype6
            - libdrm2
            - libgl1-mesa-dri
            - libglvnd0
            - libllvm12
            - libsensors5
            - libglu1-mesa
