# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenTodoList User Manual

theme:
  name: material
  logo: assets/OpenTodoList-Transparent.svg
  favicon: assets/OpenTodoList-Transparent.svg

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
