#ifndef OPENTODOLISTCORE_GLOBAL_H
#define OPENTODOLISTCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENTODOLISTCORE_LIBRARY)
#  define OPENTODOLISTCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENTODOLISTCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENTODOLISTCORE_GLOBAL_H
