OTHER_FILES += \
  qml/OpenTodoList/styles/neutral/info.json\
  qml/OpenTodoList/styles/neutral/main.qml\
  qml/OpenTodoList/styles/neutral/helper/FontLayout.qml\
  qml/OpenTodoList/styles/neutral/helper/Layout.qml\
  qml/OpenTodoList/styles/neutral/helper/ColorScheme.qml\
  qml/OpenTodoList/styles/neutral/controls/TodoView.qml\
  qml/OpenTodoList/styles/neutral/controls/ViewContainer.qml\
  qml/OpenTodoList/styles/neutral/controls/ToolButton.qml\
  qml/OpenTodoList/styles/neutral/controls/DatePicker.qml\
  qml/OpenTodoList/styles/neutral/controls/LinkLabel.qml\
  qml/OpenTodoList/styles/neutral/controls/Button.qml\
  qml/OpenTodoList/styles/neutral/controls/Popup.qml\
  qml/OpenTodoList/styles/neutral/controls/SymbolButton.qml\
  qml/OpenTodoList/styles/neutral/controls/IconButton.qml\
  qml/OpenTodoList/styles/neutral/controls/PriorityIndicator.qml\
  qml/OpenTodoList/styles/neutral/controls/SimpleTextInput.qml\
  qml/OpenTodoList/styles/neutral/controls/ProgressIndicator.qml\
  qml/OpenTodoList/styles/neutral/controls/View.qml\
  qml/OpenTodoList/styles/neutral/controls/TodoListEntry.qml\
  qml/OpenTodoList/styles/neutral/controls/Calendar.qml\
  qml/OpenTodoList/styles/neutral/controls/ProgressBar.qml\
  qml/OpenTodoList/styles/neutral/views/TodoListContents.qml\
  qml/OpenTodoList/styles/neutral/views/SearchView.qml\
  qml/OpenTodoList/styles/neutral/views/TodoDetailsView.qml\
  qml/OpenTodoList/styles/neutral/views/TodoListContentsView.qml\
  qml/OpenTodoList/styles/neutral/views/DeletedTodosView.qml\
  qml/OpenTodoList/styles/neutral/views/TodoListView.qml\
  qml/OpenTodoList/styles/neutral/views/NewTodoListView.qml\
  qml/OpenTodoList/styles/neutral/views/SettingsView.qml
