OTHER_FILES += \
  qml/OpenTodoList/main.qml\
  qml/OpenTodoList/res/fontawesome-webfont.license.txt\
  qml/OpenTodoList/res/rpdevlogo_webheader.png\
  qml/OpenTodoList/res/description.png\
  qml/OpenTodoList/res/description.svg\
  qml/OpenTodoList/res/fontawesome-webfont.ttf\
  qml/OpenTodoList/res/description.sci\
  qml/OpenTodoList/helper/FontLayout.qml\
  qml/OpenTodoList/helper/Layout.qml\
  qml/OpenTodoList/helper/ColorScheme.qml\
  qml/OpenTodoList/js/Utils.js\
  qml/OpenTodoList/controls/TodoView.qml\
  qml/OpenTodoList/controls/ViewContainer.qml\
  qml/OpenTodoList/controls/ToolButton.qml\
  qml/OpenTodoList/controls/DatePicker.qml\
  qml/OpenTodoList/controls/Button.qml\
  qml/OpenTodoList/controls/Popup.qml\
  qml/OpenTodoList/controls/SymbolButton.qml\
  qml/OpenTodoList/controls/IconButton.qml\
  qml/OpenTodoList/controls/PriorityIndicator.qml\
  qml/OpenTodoList/controls/SimpleTextInput.qml\
  qml/OpenTodoList/controls/ProgressIndicator.qml\
  qml/OpenTodoList/controls/View.qml\
  qml/OpenTodoList/controls/TodoListEntry.qml\
  qml/OpenTodoList/controls/Calendar.qml\
  qml/OpenTodoList/controls/ProgressBar.qml\
  qml/OpenTodoList/views/TodoListContents.qml\
  qml/OpenTodoList/views/SearchView.qml\
  qml/OpenTodoList/views/TodoDetailsView.qml\
  qml/OpenTodoList/views/TodoListContentsView.qml\
  qml/OpenTodoList/views/DeletedTodosView.qml\
  qml/OpenTodoList/views/TodoListView.qml\
  qml/OpenTodoList/views/NewTodoListView.qml \
    qml/OpenTodoList/controls/LinkLabel.qml
