# Set application version:
if(OPENTODOLIST_FORCE_VERSION)
    add_definitions(-DOPENTODOLIST_VERSION="${OPENTODOLIST_FORCE_VERSION}")
    set(OPENTODOLIST_VERSION ${OPENTODOLIST_FORCE_VERSION})
else()
    set(OPENTODOLIST_MAJOR 3)
    set(OPENTODOLIST_MINOR 33)
    set(OPENTODOLIST_PATCH 0)
    set(OPENTODOLIST_VERSION
        ${OPENTODOLIST_MAJOR}.${OPENTODOLIST_MINOR}.${OPENTODOLIST_PATCH})
    find_program(GIT_EXECUTABLE git)
    if(GIT_EXECUTABLE)
        execute_process(
            COMMAND
                ${GIT_EXECUTABLE} describe --tags
            OUTPUT_VARIABLE
                OPENTODOLIST_GIT_VERSION_STRING
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
        add_definitions(-DOPENTODOLIST_VERSION="${OPENTODOLIST_GIT_VERSION_STRING}")
        set(OPENTODOLIST_VERSION "${OPENTODOLIST_GIT_VERSION_STRING}")
    else()
        add_definitions(-DOPENTODOLIST_VERSION="${OPENTODOLIST_VERSION}-unknown")

    endif()
endif()

if("${OPENTODOLIST_VERSION}" STREQUAL "")
    set(OPENTODOLIST_VERSION_MAJOR 3)
    set(OPENTODOLIST_VERSION_MINOR 33)
    set(OPENTODOLIST_VERSION_PATCH 0)
else()
    string(REPLACE "." ";" OPENTODOLIST_VERSION_LIST "${OPENTODOLIST_VERSION}")
    list(GET OPENTODOLIST_VERSION_LIST 0 OPENTODOLIST_VERSION_MAJOR)
    list(GET OPENTODOLIST_VERSION_LIST 1 OPENTODOLIST_VERSION_MINOR)
    list(GET OPENTODOLIST_VERSION_LIST 2 OPENTODOLIST_VERSION_PATCH)
endif()
